### ISSUE TITLE
Getting current playback position (or percent)

### ISSUE THREAD

**Issue by cerupcat** [wbrent/timeStretch_tilde#1]
Great work on the patch @wbrent. I'm trying to see what I could get the current playback position (in samples or percent). Do you have any recommendations on what I would modify/add to get this information? Essentially, I'd like to display a hslider (for now) that shows the progress as the sound plays.

**Comment by wbrent** [comment]
Hi Seth,You can get the current playback position in milliseconds of any of the 16 voices within the [timeStretch~] abstraction by receiving "$0-timestretch-X-location-current", where X is the voice number (0-15). To get the data outside of [timeStretch~], you could receive all 16 of those and pack the data prepended with the voice number, and send the 2-element list out of an additional outlet. Then, outside you could use [route] to get the individual playback positions for any desired voice.For now, I'd add a subpatch that does the 16 receives and re-packing. But the next time I get a chance to update this I'll add an omni "location-current" send name to which all 16 voices send their locations, but prepended with their voice number. Then the omni receive can just go straight out of an outlet.And it looks like I'll need to make an update fairly soon because that samplerate command doesn't work as expected!WilliamOn November 13, 2018 at 6:57 PM Seth <notifications@github.com> wrote:  Great work on the patch @wbrent. I'm trying to see what I could get the current playback position (in samples or percent). Do you have any recommendations on what I would modify/add to get this information? Essentially, I'd like to display a hslider (for now) that shows the progress as the sound plays.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cerupcat** [comment]
Thanks for the quick reply. I was able to get the percent played output right before you responded, but it's not as elegant as a solution as you proposed, so I won't do a PR unless you want me to. I'll respond about the sample rate on the other ticket.
